# Generated by Django 4.2 on 2026-02-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('area_sqm', models.IntegerField()),
                ('solar_irradiance_kwh', models.DecimalField(decimal_places=2, max_digits=4)),
                ('grid_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slope_degrees', models.DecimalField(decimal_places=2, max_digits=4)),
                ('road_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('elevation_m', models.IntegerField()),
                ('land_type', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
